### PR TITLE
mostly mesh io

### PR DESCRIPTION
**Pull request by kwagstyl**
Hi,

Here's the not to useful mesh layers code.
Also a couple of corrections on the io_mesh with how nibabel was being used.
The minc mni writing isn't quite working yet.

### CODE REVIEW

**Comment by kwagstyl** [comment]
Also added write mesh data

**Review by juhuntenburg — COMMENTED** [review]
Hi @kwagstyl , cool thanks for this! Just a mini-question: why not importing nibabel as nb? Would be consistent with what we do in the other files.
Thanks!

**Comment by kwagstyl** [comment]
Hi @juhuntenburg ,
I think one of the functions that was in the file used nibabel not nb, and at the time I just wanted to get it to work. In retrospect keeping consistency is worth the minor extra effort so I'll go change it

**Comment by juhuntenburg** [comment]
Cool, thanks!

**Pull request merged**
